# _config.yml
# Site Settings
locale: "en-US"
title: "Sai Suresh Macharla Vasu"
title_separator: "-"
name: &name "Sai Suresh Macharla Vasu"
description: &description "LLM safety & fairness · persona/mental modeling · anomaly detection"
url: https://saisuresh1999.github.io
baseurl: ""                     # user page => keep empty
repository: "saisuresh1999/saisuresh1999.github.io"

# Theme (this is the part Christoph’s file doesn’t need but YOU do)
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "air"

teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

comments:
  provider:

# Site Author
author:
  name: "Sai Suresh Macharla Vasu"
  avatar: "profile_casual.png"   # put the file at /images/profile_casual.png
  bio: "M.Sc. DSAI @ Saarland University | Research Assistant @ DFKI IML Group | Head Tutor @ UdS"
  location: "Saarbrücken, Germany"
  employer: "Saarland University · DFKI"
  email: "sama00014@stud.uni-saarland.de"
  googlescholar: "https://scholar.google.com/citations?user=rm5fF-gAAAAJ&hl=en"
  orcid: "https://orcid.org/0009-0009-4051-1597"
  github: "saisuresh1999"
  linkedin: "sai-suresh-macharla-vasu"
  twitter: "saisuresh1999"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - .github
  - node_modules
  - vendor
  - tmp
  - local
  - log
  - Dockerfile
  - Gemfile
  - README
  - package.json*
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:     { output: true, permalink: /:collection/:path/ }
  publications: { output: true, permalink: /:collection/:path/ }
  portfolio:    { output: true, permalink: /:collection/:path/ }
  talks:        { output: true, permalink: /:collection/:path/ }

# Defaults
defaults:
  - scope: { path: "", type: posts }
    values: { layout: single, author_profile: true, read_time: true, comments: true, share: true, related: true }
  - scope: { path: "", type: pages }
    values: { layout: single, author_profile: true }
  - scope: { path: "", type: teaching }
    values: { layout: single, author_profile: true, share: true, comments: true }
  - scope: { path: "", type: publications }
    values: { layout: single, author_profile: true, share: true, comments: true }
  - scope: { path: "", type: portfolio }
    values: { layout: single, author_profile: true, share: true, comment: true }
  - scope: { path: "", type: talks }
    values: { layout: talk, author_profile: true, share: true }

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Europe/Berlin

# GitHub Pages–supported plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-include-cache

# Archives
category_archive: { type: liquid, path: /categories/ }
tag_archive:      { type: liquid, path: /tags/ }

# HTML Compression
compress_html:
  clippings: all
  ignore: { envs: development }
